name: webconto-tg-bot
services:
  api:
    image: nottheoutsider/webc_tgbot:1.2
    command: ["python", "-m", "services.api.api"]
    ports:
      - "5000:5000"  # API listens on port 5000
    environment:
      - URI=${URI}
      - CHAT_ID=${CHAT_ID}
      - TOKEN=${TOKEN}
    networks:
      - app-network

  bot:
    image: nottheoutsider/webc_tgbot:1.2
    command: ["python", "-m", "services.bot.bot"]
    depends_on:
      - api
    # No ports mapping for bot unless needed
    environment:
      - URI=${URI}
      - CHAT_ID=${CHAT_ID}
      - TOKEN=${TOKEN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge