version: '3.13.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "services.api.api"]
    ports:
      - "5000:5000"  # Map host port 8000 to container port 8000 for FastAPI
    volumes:
      - .:/app
    environment:
      - URI=${URI}  # MongoDB URI from .env
      - CHAT_ID=${CHAT_ID}  # Telegram chat ID if needed
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "services.bot.bot"]
    depends_on:
      - api
    volumes:
      - .:/app
    environment:
      - URI=${URI}
      - CHAT_ID=${CHAT_ID}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge